### ISSUE TITLE
Pls add G29 or G920 PC Support

### ISSUE THREAD

**Issue by LDprg** [matlo/GIMX-firmwares#7] opened 2021-06-05 17:54 UTC
Hi!
Emulating a G27 works perfekt, I have used it for playing games with my old Formel Professional wheel and really like your software, but now there are games which have only support for G29 or G920. So I can't play them without remapping the g27 to a XBOX Controller (to mention a game for example Need for Speed Heat). 
So please create a G29 PC or G920 PC firmware that allows to emulate one of those.  
Thanks in advance!

PS: I have tried to use the G29 PS4 emulator (I know your website says that it won't work on PC) for PC, but it only tells me that no DS4 Controller is connected (I have no one).

**Comment by matlo** [comment] 2021-08-30 20:23
Duplicate of matlo/GIMX#683.

**Closed as completed by matlo** 2021-08-30 20:23 UTC
